version: '3.8'

services:
  postgres:
    image: postgres
    container_name: housekeeper_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: housekeeperdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass

  pgadmin:
    image: dpage/pgadmin4
    container_name: housekeeper_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
